### ISSUE TITLE
Combine waves?

### ISSUE THREAD

**Issue by caleb-allen** [benmoran56/chippy#2]
Awesome library!

Would there be a way to combine 2 waves? It seems easy to do so sequentially (wave A and then wave B). Is there any way to combine both in parallel? (Play both A and B at once?)

Thanks in advance

**Comment by benmoran56** [comment]
Hi caleb,

I'm glad you find this useful. In answer to your question, yes, you can do this quite easily. (I really need to write up some proper documentation at some point). There is a Synthesizer.composite_generator method, which takes 2+ generators as input, and gives you a new generator with their composited output. You can then manually give that generator to Synthesizer.pack_pcm_data, and then save the pcm data with Synthesizer.save_wave. A complete example is: 

```
>>> import chippy
>>> synth = chippy.Synthesizer()
>>> combined_gen = synth.composite_generator(synth.sine_generator(220), synth.sine_generator(440))
>>> raw_pcm = synth.pack_pcm_data(wave_generator=combined_gen, length=2)
>>> synth.save_wave(raw_pcm, "combined.wav")
saved file: combined.wav 
```

**Comment by caleb-allen** [comment]
Oh, wow, that's exactly what I was looking for! Guess I wasn't looking close enough. Thanks! Great library
